on:
  workflow_call:
    secrets:
      aws_assume_role:
        description: "AWS role to assume"
        required: false
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
jobs:
  diff:
    runs-on: ubuntu-latest
    container: # Replace with GitHub action in the future
      image: public.ecr.aws/truemark/aws-cdk:ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "${{ secrets.aws_assume_role }}"
          aws-region: "us-east-2"

      - name: CDK Diff
        run: |
          cd cdk
          pnpm i --frozen-lockfile
          cdk -c env=${{ inputs.environment }} diff
